# Generated by Django 4.0.6 on 2022-08-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
