# Generated by Django 4.0.6 on 2022-08-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_updated_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.IntegerField(default=4),
        ),
    ]
