# Generated by Django 4.0.6 on 2022-08-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity_now',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
