# Generated by Django 4.0.6 on 2022-08-01 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
