# Generated by Django 4.0.6 on 2022-08-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_dt',
        ),
    ]
