# Generated by Django 4.0.6 on 2022-08-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
