# Generated by Django 4.0.6 on 2022-08-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
