# Generated by Django 4.0.6 on 2022-08-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'C'), ('order', 'O'), ('wishlist', 'W')], default='cart', max_length=10),
        ),
    ]
